# Generated by Django 4.1.1 on 2022-09-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('numero_processo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('classe', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('assunto', models.CharField(blank=True, max_length=50, null=True)),
                ('data_de_distribuicao', models.CharField(blank=True, max_length=50, null=True)),
                ('juiz', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_da_acao', models.CharField(blank=True, max_length=50, null=True)),
                ('partes_do_processo', models.TextField(blank=True, null=True)),
                ('lista_das_movimentacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crawler',
                'managed': False,
            },
        ),
    ]
